# Browser Configuration
browser=chrome
headless=false

# Application URL
base.url=https://automationexercise.com

# Test Credentials (used only for local execution)
valid.email=your-email@example.com
valid.password=your-password

invalid.email=invalid@test.com
invalid.password=invalid123

# Timeouts
implicit.wait=5
explicit.wait=15
page.load.timeout=30